In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [34]:
df = pd.read_csv("/content/input_data (2).csv")

In [35]:
df = df.drop(df.columns[0], axis = 1)

In [37]:
df.sort_values(by="Date", inplace=True)

In [51]:
df.dtypes

Date                datetime64[ns]
Open                       float64
High                       float64
Low                        float64
Close                      float64
Daily Returns              float64
Daily Volatility           float64
Adj Close                  float64
Volume                       int64
Dividends                  float64
Stock Splits               float64
ticker                      object
wihtin_30                    int64
dtype: object

In [48]:
df["Date"].str.strip()

AttributeError: Can only use .str accessor with string values!

In [47]:
df["Date"] = pd.to_datetime(df["Date"].str.strip())

AttributeError: Can only use .str accessor with string values!

In [38]:
df.head()

,Date,Open,High,Low,Close,Daily Returns,Daily Volatility,Monthly Volatility,Adj Close,Volume,Dividends,Stock Splits,ticker,wihtin_30
0,2020-01-08,86.239998,86.660004,85.930000,86.209999,0.004076,0.008283,0.010128,77.151642,5693900,0.0,0.0,ABT,0
243368,2020-01-08,70.110001,70.290001,69.169998,69.230003,-0.015080,0.009634,0.008844,52.397743,15137700,0.0,0.0,XOM,0
423393,2020-01-08,14.470000,14.680000,14.470000,14.540000,0.002759,0.005942,0.013332,13.676484,1695900,0.0,0.0,NWSA,0
533058,2020-01-08,18.004000,18.438000,18.004000,18.341999,0.018887,0.016192,0.010504,16.694996,7247500,0.0,0.0,TSCO,0
74271,2020-01-08,34.570000,35.189999,34.549999,34.970001,0.010110,0.012802,0.011212,30.182205,45311600,0.0,0.0,BAC,0

In [39]:
df.head()

,Date,Open,High,Low,Close,Daily Returns,Daily Volatility,Monthly Volatility,Adj Close,Volume,Dividends,Stock Splits,ticker,wihtin_30
0,2020-01-08,86.239998,86.660004,85.930000,86.209999,0.004076,0.008283,0.010128,77.151642,5693900,0.0,0.0,ABT,0
243368,2020-01-08,70.110001,70.290001,69.169998,69.230003,-0.015080,0.009634,0.008844,52.397743,15137700,0.0,0.0,XOM,0
423393,2020-01-08,14.470000,14.680000,14.470000,14.540000,0.002759,0.005942,0.013332,13.676484,1695900,0.0,0.0,NWSA,0
533058,2020-01-08,18.004000,18.438000,18.004000,18.341999,0.018887,0.016192,0.010504,16.694996,7247500,0.0,0.0,TSCO,0
74271,2020-01-08,34.570000,35.189999,34.549999,34.970001,0.010110,0.012802,0.011212,30.182205,45311600,0.0,0.0,BAC,0

In [40]:
y = df["Monthly Volatility"]

In [41]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Daily Returns',
       'Daily Volatility', 'Monthly Volatility', 'Adj Close', 'Volume',
       'Dividends', 'Stock Splits', 'ticker', 'wihtin_30'],
      dtype='object')

In [42]:
df.drop(columns="Monthly Volatility", inplace=True)

In [43]:
x_train, x_test, y_train, y_test = train_test_split(df, y, test_size=0.3, random_state=42)

In [44]:
train_csv = x_train
train_csv["monthly_volatility"] = y_train
train_csv.to_csv("train.csv", index=False)

In [45]:
test_csv = x_test
test_csv["monthly_volatility"] = y_test
test_csv.to_csv("test.csv", index = False)